# Roundhouse default — latest vanilla Minecraft
level-name=worlds/world
server-port=25565
motd=A Minecraft Server
max-players=20
view-distance=10
simulation-distance=10
spawn-protection=0
difficulty=normal
gamemode=survival
hardcore=false
pvp=true
online-mode=true
white-list=false
enforce-whitelist=false
allow-nether=true
enable-command-block=false
enable-status=true
enforce-secure-profile=false
sync-chunk-writes=true
server-ip=
enable-rcon=false
enable-query=false
allow-flight=false
