# Minecraft Java server properties
# Vanilla runtime on Railway

level-name=world
server-port=25565
motd=Vanilla Minecraft server on Railway
max-players=20
view-distance=10
simulation-distance=10
spawn-protection=0
difficulty=normal
gamemode=survival
hardcore=false
pvp=true
online-mode=true
white-list=false
allow-nether=true
enable-command-block=false
enable-status=true
enforce-secure-profile=false
sync-chunk-writes=true
